=== nagymate400/CWM4U0_XMLGYAK/XMLTaskCWM4U0/XMLSchemaCWM4U0.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Elofizetok">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Elofizeto" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Nev"/>
                    <xs:element type="xs:string" name="Utca"/>
                    <xs:element type="xs:byte" name="Hazszam"/>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="ElofizetoId" use="optional"/>
                  <xs:attribute type="xs:byte" name="ElofizetesId" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Elofizetesek">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Elofizetes" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="Lapid"/>
                    <xs:element type="xs:byte" name="Eloid"/>
                    <xs:element name="Elofizetok">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:byte" name="Db"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="ElofizetesId" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Kihordok">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Kihordo" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Knev"/>
                    <xs:element type="xs:byte" name="Kbeosztas"/>
                    <xs:element type="xs:string" name="Varos"/>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="Kihordoid" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Szerkesztok">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Szerkeszto" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Sznev"/>
                    <xs:element type="xs:string" name="Szbeosztas"/>
                    <xs:element type="xs:string" name="Szadatok"/>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="SzerkesztoId" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Lapok">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Lap" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Cim"/>
                    <xs:element type="xs:string" name="Tema"/>
                    <xs:element type="ar" name="Havi"/>
                    <xs:element type="ar" name="Negyedeves"/>
                    <xs:element type="xs:byte" name="Szid"/>
                    <xs:element type="xs:byte" name="Kid"/>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="LapId" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="E-Ek">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="E-E" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:byte" name="ElofizetoId" use="optional"/>
                      <xs:attribute type="xs:byte" name="ElofizetesId" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="L-Kk">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="L-K" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:byte" name="LapId" use="optional"/>
                      <xs:attribute type="xs:byte" name="Kihordoid" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="L-Szk">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="L-Sz" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:byte" name="LapId" use="optional"/>
                      <xs:attribute type="xs:byte" name="SzerkesztoId" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="E-Lk">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
              <xs:element name="E-L">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Ajandek"/>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="LapId" use="optional"/>
                  <xs:attribute type="xs:byte" name="ElofizetesId" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="Kihordo_Key">
      <xs:selector xpath="Kihordo"/>
      <xs:field xpath="@DId"/>
    </xs:key>
    <xs:key name="Elofizeto_Key">
      <xs:selector xpath="Elofizeto"/>
      <xs:field xpath="@DId"/>
    </xs:key>
    <xs:key name="Elofizetes_Key">
      <xs:selector xpath="Elofizetes"/>
      <xs:field xpath="@DId"/>
    </xs:key>
    <xs:key name="Lap_Key">
      <xs:selector xpath="Lap"/>
      <xs:field xpath="@DId"/>
    </xs:key>
    <xs:key name="Szerkeszto_Key">
      <xs:selector xpath="Szerkeszto"/>
      <xs:field xpath="@DId"/>
    </xs:key>
    <xs:keyref name="Fkey_Lap_Kihordo" refer="Kihordo_Key">
      <xs:selector xpath="Lap"/>
      <xs:field xpath="@Id"/>
    </xs:keyref>
    <xs:keyref name="Fkey_Elofizetes_Elofizeto" refer="Elofizeto_Key">
      <xs:selector xpath="Elofizetes"/>
      <xs:field xpath="@Id"/>
    </xs:keyref>
    <xs:keyref name="Fkey_Lap_Szerkeszto" refer="Szerkeszto_Key">
      <xs:selector xpath="Lap"/>
      <xs:field xpath="@Id"/>
    </xs:keyref>
    <xs:keyref name="Fkey_Elofizetes_Lap" refer="Elofizetes_Key">
      <xs:selector xpath="Lap"/>
      <xs:field xpath="@Id"/>
    </xs:keyref>
  </xs:element>
  <xs:simpleType name="ar">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="100000"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== nagymate400/CWM4U0_XMLGYAK/XMLTaskCWM4U0/DOMParseCWM4U0/XMLcwm4u0mod.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaCWM4U0.xsd">
<Elofizetok>
    <Elofizeto ElofizetesId="1" ElofizetoId="1">
        <Nev>Béla</Nev>
        <Utca>Eper</Utca>
        <Hazszam>1</Hazszam>
    </Elofizeto>
    <Elofizeto ElofizetesId="2" ElofizetoId="2">
        <Nev>Bence</Nev>
        <Utca>Eper</Utca>
        <Hazszam>2</Hazszam>
    </Elofizeto>
    <Elofizeto ElofizetesId="3" ElofizetoId="3">
        <Nev>Lajos</Nev>
        <Utca>Eper</Utca>
        <Hazszam>3</Hazszam>
    </Elofizeto>
</Elofizetok>
<Elofizetesek>
    <Elofizetes ElofizetesId="1">
        <Lapid>1</Lapid>
        <Eloid>1</Eloid>
        <Elofizetok>
            <Db>1</Db>
        </Elofizetok>
    </Elofizetes>
    <Elofizetes ElofizetesId="2">
        <Lapid>2</Lapid>
        <Eloid>2</Eloid>
        <Elofizetok>
            <Db>2</Db>
        </Elofizetok>
    </Elofizetes>
    <Elofizetes ElofizetesId="3">
        <Lapid>3</Lapid>
        <Eloid>3</Eloid>
        <Elofizetok>
            <Db>3</Db>
        </Elofizetok>
    </Elofizetes>
</Elofizetesek>
<Kihordok>
    <Kihordo Kihordoid="1">
        <Knev>Endre</Knev>
        <Kbeosztas>1</Kbeosztas>
        <Varos>Miskolc</Varos>
    </Kihordo>
    <Kihordo Kihordoid="2">
        <Knev>Lajos</Knev>
        <Kbeosztas>2</Kbeosztas>
        <Varos>Budapest</Varos>
    </Kihordo>
    <Kihordo Kihordoid="3">
        <Knev>Milán</Knev>
        <Kbeosztas>3</Kbeosztas>
        <Varos>Miskolc</Varos>
    </Kihordo>
</Kihordok>
<Szerkesztok>
    <Szerkeszto SzerkesztoId="1">
        <Sznev>Imre</Sznev>
        <Szbeosztas>Sport elemzo</Szbeosztas>
        <Szadatok>Egyetemi végzettség</Szadatok>
    </Szerkeszto>
    <Szerkeszto SzerkesztoId="2">
        <Sznev>Ferenc</Sznev>
        <Szbeosztas>Riporter</Szbeosztas>
        <Szadatok>Középiskolai végzettség</Szadatok>
    </Szerkeszto>
    <Szerkeszto SzerkesztoId="3">
        <Sznev>Erik</Sznev>
        <Szbeosztas>Designer</Szbeosztas>
        <Szadatok>Egyetemi végzettség</Szadatok>
    </Szerkeszto>
</Szerkesztok>
<Lapok>
    <Lap LapId="1">
        <Cim>Nemzeti sport</Cim>
        <Tema>Sport</Tema>
        <Havi>6000</Havi>
        <Negyedeves>17850</Negyedeves>
        <Szid>1</Szid>
        <Kid>1</Kid>
    </Lap>
    <Lap LapId="2">
        <Cim>PC World</Cim>
        <Tema>Informatika</Tema>
        <Havi>1800</Havi>
        <Negyedeves>5385</Negyedeves>
        <Szid>2</Szid>
        <Kid>2</Kid>
    </Lap>
    <Lap LapId="3">
        <Cim>Mi Újság</Cim>
        <Tema>Hírek</Tema>
        <Havi>1500</Havi>
        <Negyedeves>5000</Negyedeves>
        <Szid>3</Szid>
        <Kid>3</Kid>
    </Lap>
</Lapok>
<E-Ek>
    <E-E ElofizetesId="1" ElofizetoId="1">
    </E-E>
    <E-E ElofizetesId="2" ElofizetoId="2">
    </E-E>
    <E-E ElofizetesId="3" ElofizetoId="3">
    </E-E>
</E-Ek>
<L-Kk>
    <L-K Kihordoid="1" LapId="1">
    </L-K>
    <L-K Kihordoid="2" LapId="2">
    </L-K>
    <L-K Kihordoid="3" LapId="3">
    </L-K>
</L-Kk>
<L-Szk>
    <L-Sz LapId="1" SzerkesztoId="1">
    </L-Sz>
    <L-Sz LapId="2" SzerkesztoId="2">
    </L-Sz>
    <L-Sz LapId="3" SzerkesztoId="3">
    </L-Sz>
</L-Szk>
<E-Lk>
    <E-L ElofizetesId="1" LapId="1">
        <Ajandek>Nincs</Ajandek>
    </E-L>
    <E-L ElofizetesId="2" LapId="2">
        <Ajandek>Van</Ajandek>
    </E-L>
    <E-L ElofizetesId="3" LapId="3">
        <Ajandek>Nincs</Ajandek>
    </E-L>
</E-Lk>
</root>

=== nagymate400/CWM4U0_XMLGYAK/XMLTaskCWM4U0/DOMParseCWM4U0/XMLcwm4u0.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaCWM4U0.xsd">
<Elofizetok>
    <Elofizeto ElofizetoId="1" ElofizetesId="1">
        <Nev>Gábor</Nev>
        <Utca>Eper</Utca>
        <Hazszam>1</Hazszam>
    </Elofizeto>
    <Elofizeto ElofizetoId="2" ElofizetesId="2">
        <Nev>Bence</Nev>
        <Utca>Eper</Utca>
        <Hazszam>2</Hazszam>
    </Elofizeto>
    <Elofizeto ElofizetoId="3" ElofizetesId="3">
        <Nev>Lajos</Nev>
        <Utca>Eper</Utca>
        <Hazszam>3</Hazszam>
    </Elofizeto>
</Elofizetok>
<Elofizetesek>
    <Elofizetes  ElofizetesId="1">
        <Lapid>1</Lapid>
        <Eloid>1</Eloid>
        <Elofizetok>
            <Db>1</Db>
        </Elofizetok>
    </Elofizetes>
    <Elofizetes ElofizetesId="2">
        <Lapid>2</Lapid>
        <Eloid>2</Eloid>
        <Elofizetok>
            <Db>2</Db>
        </Elofizetok>
    </Elofizetes>
    <Elofizetes ElofizetesId="3">
        <Lapid>3</Lapid>
        <Eloid>3</Eloid>
        <Elofizetok>
            <Db>3</Db>
        </Elofizetok>
    </Elofizetes>
</Elofizetesek>
<Kihordok>
    <Kihordo Kihordoid="1">
        <Knev>Endre</Knev>
        <Kbeosztas>1</Kbeosztas>
        <Varos>Miskolc</Varos>
    </Kihordo>
    <Kihordo Kihordoid="2">
        <Knev>Lajos</Knev>
        <Kbeosztas>2</Kbeosztas>
        <Varos>Budapest</Varos>
    </Kihordo>
    <Kihordo Kihordoid="3">
        <Knev>Milán</Knev>
        <Kbeosztas>3</Kbeosztas>
        <Varos>Miskolc</Varos>
    </Kihordo>
</Kihordok>
<Szerkesztok>
    <Szerkeszto SzerkesztoId="1">
        <Sznev>Imre</Sznev>
        <Szbeosztas>Sport elemzo</Szbeosztas>
        <Szadatok>Egyetemi végzettség</Szadatok>
    </Szerkeszto>
    <Szerkeszto SzerkesztoId="2">
        <Sznev>Ferenc</Sznev>
        <Szbeosztas>Riporter</Szbeosztas>
        <Szadatok>Középiskolai végzettség</Szadatok>
    </Szerkeszto>
    <Szerkeszto SzerkesztoId="3">
        <Sznev>Erik</Sznev>
        <Szbeosztas>Designer</Szbeosztas>
        <Szadatok>Egyetemi végzettség</Szadatok>
    </Szerkeszto>
</Szerkesztok>
<Lapok>
    <Lap LapId="1">
        <Cim>Nemzeti sport</Cim>
        <Tema>Sport</Tema>
        <Havi>6000</Havi>
        <Negyedeves>17850</Negyedeves>
        <Szid>1</Szid>
        <Kid>1</Kid>
    </Lap>
    <Lap LapId="2">
        <Cim>PC World</Cim>
        <Tema>Informatika</Tema>
        <Havi>1800</Havi>
        <Negyedeves>5385</Negyedeves>
        <Szid>2</Szid>
        <Kid>2</Kid>
    </Lap>
    <Lap LapId="3">
        <Cim>Mi Újság</Cim>
        <Tema>Hírek</Tema>
        <Havi>1500</Havi>
        <Negyedeves>5000</Negyedeves>
        <Szid>3</Szid>
        <Kid>3</Kid>
    </Lap>
</Lapok>
<E-Ek>
    <E-E ElofizetoId="1" ElofizetesId="1">
    </E-E>
    <E-E ElofizetoId="2" ElofizetesId="2">
    </E-E>
    <E-E ElofizetoId="3" ElofizetesId="3">
    </E-E>
</E-Ek>
<L-Kk>
    <L-K LapId="1" Kihordoid="1">
    </L-K>
    <L-K LapId="2" Kihordoid="2">
    </L-K>
    <L-K LapId="3" Kihordoid="3">
    </L-K>
</L-Kk>
<L-Szk>
    <L-Sz LapId="1" SzerkesztoId="1">
    </L-Sz>
    <L-Sz LapId="2" SzerkesztoId="2">
    </L-Sz>
    <L-Sz LapId="3" SzerkesztoId="3">
    </L-Sz>
</L-Szk>
<E-Lk>
    <E-L LapId="1" ElofizetesId="1">
        <Ajandek>Nincs</Ajandek>
    </E-L>
    <E-L LapId="2" ElofizetesId="2">
        <Ajandek>Van</Ajandek>
    </E-L>
    <E-L LapId="3" ElofizetesId="3">
        <Ajandek>Nincs</Ajandek>
    </E-L>
</E-Lk>
</root>
